设备巡检/users/urls.py
"""为应用程序users定义URL模式"""

from django.urls import path
from django.contrib.auth.views import LoginView
from django.conf.urls import include

from . import views

urlpatterns = [
    # 登录界面
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),

    # 注销
    path('logout/', views.logout_view, name='logout'),

    # 注册
    path('register', views.register, name='register'),
]

设备巡检/xunjian/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('xunjiansys.urls', 'xunjiansys'), namespace='xunjiansys')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

设备巡检/xunjiansys/urls.py
"""定义xunjiansys的URL模式"""

from django.urls import path
from . import views

urlpatterns = [
    # 主页
    path(r'', views.index, name='index'),

    # 设备清单
    path(r'equipments/', views.equipments, name='equipments'),

    # 设备详情页
    path(r'equipments/<equipment_no>/', views.equipment_detail, name='equipment_detail'),

    # 添加新设备
    path(r'add_equipment/', views.add_equipment, name='add_equipment'),

    # 添加新巡检记录
    path(r'add_record/', views.add_record, name='add_record'),

    # 巡检记录清单
    path(r'records/', views.records, name='records'),

]

设备巡检/users/models.py
from django.db import models

# Create your models here.

设备巡检/xunjiansys/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.functions import TruncTime, TruncSecond


# Create your models here.
class Location_type(models.Model):
    """位置类型"""
    lt_name = models.CharField(max_length=100, verbose_name='位置类型')

    def __str__(self):
        """返回字符串类型"""
        return self.lt_name

    class Meta:
        verbose_name = '位置类型'
        verbose_name_plural = '位置类型'


class Floor(models.Model):
    """楼层信息"""
    f_name = models.CharField(max_length=100, verbose_name='楼层')

    def __str__(self):
        """返回字符串类型"""
        return self.f_name

    class Meta:
        verbose_name = '所在楼层'
        verbose_name_plural = '所在楼层'


class Equipment(models.Model):
    """设备信息"""
    no = models.CharField(max_length=100, verbose_name='设备编码')
    type = models.CharField(max_length=100, verbose_name='设备类型')
    name = models.CharField(max_length=100, verbose_name='设备名称')
    floor = models.ForeignKey(Floor, verbose_name='所在楼层', on_delete=models.DO_NOTHING)
    location_type = models.ForeignKey(Location_type, verbose_name='位置类型', on_delete=models.DO_NOTHING)
    location = models.CharField(max_length=100, verbose_name='具体位置')
    state = models.CharField(max_length=10, verbose_name='设备状态')
    date_create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.no + ' ' + self.name

    class Meta:
        verbose_name = '设备'
        verbose_name_plural = '设备'


class Record(models.Model):
    """巡检记录"""
    equipment = models.ForeignKey(Equipment, on_delete=models.DO_NOTHING, verbose_name='设备ID')
    users = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name='巡检人员')
    mhq_state = models.BooleanField(default=True, verbose_name='灭火器状态')
    xhs_state = models.BooleanField(default=True, verbose_name='消火栓状态')
    wg_state = models.BooleanField(default=True, verbose_name='外观及标识状态')
    date_create = models.DateTimeField(auto_now_add=True)  # 记录生成时间

    def __str__(self):
        """返回模型的字符串表示"""
        return self.equipment.no + ' ' + str(self.date_create)

    class Meta:
        verbose_name = '巡检记录'
        verbose_name_plural = '巡检记录'

设备巡检/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('xunjiansys:index'))


def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填好的表单
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，再重定向到主页
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('xunjiansys:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

设备巡检/xunjiansys/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
from xunjiansys.form import EquipmentForm, RecordForm
from xunjiansys.models import Equipment, Record


def index(request):
    """巡检系统主页"""
    return render(request, 'xunjiansys/index.html')


@login_required
def equipments(request):
    """设备列表页"""
    equipments = Equipment.objects.order_by('date_create')
    context = {'equipments': equipments}
    return render(request, 'xunjiansys/equipments.html', context)


@login_required
def equipment_detail(request, equipment_no):
    """显示单个设备的详细信息"""
    equipment = Equipment.objects.get(no=equipment_no)
    records = Record.objects.get(equipment=equipment)
    context = {'equipment': equipment, 'records': records}

    return render(request, 'xunjiansys/equipment_detail.html', context)


def add_equipment(request):
    """添加新设备"""
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = EquipmentForm()
    else:
        # POST提交的数据，对数据进行处理并保存
        form = EquipmentForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('xunjiansys:equipments'))

    context = {'form': form}
    return render(request, 'xunjiansys/add_equipment.html', context)


def records(request):
    """显示某设备的巡检记录"""
    records = Record.objects.order_by('date_create')
    context = {'records': records}
    return render(request, 'xunjiansys/records.html', context)


def add_record(request, equipment_no):
    """添加新巡检记录"""
    if request.method != 'POST':
        # 创建一个空表单
        form = RecordForm()
    else:
        # 对POST提交的数据进行处理
        form = RecordForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('xunjiansys:records'))

    context = {'form': form}
    return render(request, 'xunjiansys/add_record.html', context)

设备巡检/users/templates/users/login.html
{% extends "xunjiansys/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:login' %}" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
        <button name="submit" class="btn btn-primary">log in</button>
      {% endbuttons %}
      <input type="hidden" name="next" value="{% url 'xunjiansys:index' %}" />
  </form>

{% endblock content %}

设备巡检/users/templates/users/register.html
{% extends "xunjiansys/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h3>Register an account</h3>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
        <button name="submit" class="btn btn-primary">register</button>
      {% endbuttons %}
      <input type="hidden" name="next" value="{% url 'xunjiansys:index' %}" />
  </form>

{% endblock content %}

设备巡检/xunjiansys/templates/xunjiansys/add_equipment.html
{% extends "xunjiansys/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>新增设备:</h2>
{% endblock header %}



{% block content %}

  <form action="{% url 'xunjiansys:add_equipment' %}" method="post" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
        <button name="submit" class="btn btn-primary">add topic</button>
      {% endbuttons %}

  </form>
<!--  <p>Add a new topic</p>-->
<!--  <form action="{% url 'xunjiansys:add_equipment' %}" method="post">-->
<!--      {% csrf_token %}-->
<!--      {{ form.as_p }}-->
<!--      <button name="submit">创建</button>-->
<!--  </form>-->
{% endblock content %}

设备巡检/xunjiansys/templates/xunjiansys/add_record.html
{% extends "xunjiansys/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>新增巡检记录:</h2>
{% endblock header %}



{% block content %}

  <form action="{% url 'xunjiansys:add_record' %}" method="post" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
        <button name="submit" class="btn btn-primary">add topic</button>
      {% endbuttons %}

  </form>
<!--  <p>Add a new topic</p>-->
<!--  <form action="{% url 'xunjiansys:add_equipment' %}" method="post">-->
<!--      {% csrf_token %}-->
<!--      {{ form.as_p }}-->
<!--      <button name="submit">创建</button>-->
<!--  </form>-->
{% endblock content %}

设备巡检/xunjiansys/templates/xunjiansys/base.html
<!DOCTYPE html>
{% load bootstrap3 %}
<html lang="zh-cn">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <title>巡检系统</title>
      {% bootstrap_css %}
      {% bootstrap_javascript %}
  </head>

  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#navbar" aria-expanded="false" aria-controls="navbar"></button>
                <a class="navbar-brand" href="{% url 'xunjiansys:index' %}">巡检</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'xunjiansys:equipments' %}">巡检设备</a></li>
                    <li><a href="{% url 'xunjiansys:equipments' %}">巡检记录</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a>Hello,{{user.username}}</a></li>
                        <li><a href="{% url 'users:logout' %}">退出</a></li>
                    {% else %}
                        <li><a href="{% url 'users:register' %}">注册</a></li>
                        <li><a href="{% url 'users:login' %}">登录</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.nav-collapse -->
        </div>
    </nav>

    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div><!-- /container -->
  </body>

</html>

设备巡检/xunjiansys/templates/xunjiansys/equipment_detail.html
{% extends 'xunjiansys/base.html' %}

{% load bootstrap3 %}

{% block header %}
  <h2>{{ equipment }}</h2>
{% endblock header %}

{% block content %}



{% endblock content %}

设备巡检/xunjiansys/templates/xunjiansys/equipments.html
{% extends 'xunjiansys/base.html' %}

{% load bootstrap3 %}

{% block header %}
  <h2>设备清单</h2>
{% endblock header %}

{% block content %}

  <h3><a href="{% url 'xunjiansys:add_equipment' %}">添加设备</a></h3>

  <ul>
    {% for equipment in equipments %}
      <li>
        <h3>
          <a href="{% url 'xunjiansys:equipment_detail' equipment.no %}">{{ equipment }}</a>
        </h3>
      </li>
    {% empty %}
      <li>尚未添加设备</li>
    {% endfor %}
  </ul>

{% endblock content %}

设备巡检/xunjiansys/templates/xunjiansys/index.html
{% extends 'xunjiansys/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>欢迎使用巡检系统</h2>
{% endblock header %}

{% block content %}
  <small>欢迎光临</small>
{% endblock content %}

设备巡检/xunjiansys/templates/xunjiansys/record.html
{% extends 'xunjiansys/base.html' %}

{% load bootstrap3 %}

{% block header %}
  <h2>{{ record }}</h2>
{% endblock header %}

{% block content %}



{% endblock content %}

设备巡检/xunjiansys/templates/xunjiansys/records.html
{% extends 'xunjiansys/base.html' %}

{% load bootstrap3 %}

{% block header %}
  <h2>巡检记录：</h2>
{% endblock header %}

{% block content %}

  <ul>
    {% for record in records %}
      <li>
        <h3>
          <a href="{% url 'xunjiansys:record' record.id %}">{{ record }}</a>
        </h3>
      </li>
    {% empty %}
      <li>尚未添加设备</li>
    {% endfor %}
  </ul>

{% endblock content %}